apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcp-server
  namespace: ops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mcp-server-role
  namespace: ops
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mcp-server-rb
  namespace: ops
subjects:
  - kind: ServiceAccount
    name: mcp-server
    namespace: ops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mcp-server-role
