apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: ops
spec:
  replicas: 1
  selector:
    matchLabels: { app: postgres }
  template:
    metadata:
      labels: { app: postgres }
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: POSTGRES_DB
          valueFrom: { secretKeyRef: { name: pg-secret, key: DB_NAME } }
        - name: POSTGRES_USER
          valueFrom: { secretKeyRef: { name: pg-secret, key: DB_USER } }
        - name: POSTGRES_PASSWORD
          valueFrom: { secretKeyRef: { name: pg-secret, key: DB_PASS } }
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pgdata
        emptyDir: {}  
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ops
spec:
  selector: { app: postgres }
  ports:
  - name: pg
    port: 5432
    targetPort: 5432
